config/routes.rb
Rails.application.routes.draw do
  resources :gizmos
  resources :accounts
  devise_for :users
  root to: "accounts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gizmo.rb
class Gizmo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #:confirmable, :lockable, :timeoutable, :trackable and :omniauthable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :user_id, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gizmos_controller.rb
class GizmosController < ApplicationController
  before_action :set_gizmo, only: %i[ show edit update destroy ]

  # GET /gizmos or /gizmos.json
  def index
    @gizmos = Gizmo.all
  end

  # GET /gizmos/1 or /gizmos/1.json
  def show
  end

  # GET /gizmos/new
  def new
    @gizmo = Gizmo.new
  end

  # GET /gizmos/1/edit
  def edit
  end

  # POST /gizmos or /gizmos.json
  def create
    @gizmo = Gizmo.new(gizmo_params)

    respond_to do |format|
      if @gizmo.save
        format.html { redirect_to @gizmo, notice: "Gizmo was successfully created." }
        format.json { render :show, status: :created, location: @gizmo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gizmo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gizmos/1 or /gizmos/1.json
  def update
    respond_to do |format|
      if @gizmo.update(gizmo_params)
        format.html { redirect_to @gizmo, notice: "Gizmo was successfully updated." }
        format.json { render :show, status: :ok, location: @gizmo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gizmo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gizmos/1 or /gizmos/1.json
  def destroy
    @gizmo.destroy
    respond_to do |format|
      format.html { redirect_to gizmos_url, notice: "Gizmo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gizmo
      @gizmo = Gizmo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gizmo_params
      params.require(:gizmo).permit(:type, :title, :bool1, :string1)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gizmos_helper.rb
module GizmosHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Name:</strong>
    <%= account.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= account.user_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= account.status %>
  </p>

  <p>
    <%= link_to "Show this account", account %>
  </p>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <%= render @accounts %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", account_path(@account), method: :delete %>
</div>

app/views/gizmos/_form.html.erb
<%= form_with(model: gizmo) do |form| %>
  <% if gizmo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gizmo.errors.count, "error") %> prohibited this gizmo from being saved:</h2>

      <ul>
        <% gizmo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :bool1, style: "display: block" %>
    <%= form.check_box :bool1 %>
  </div>

  <div>
    <%= form.label :string1, style: "display: block" %>
    <%= form.text_field :string1 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gizmos/_gizmo.html.erb
<div id="<%= dom_id gizmo %>">
  <p>
    <strong>Type:</strong>
    <%= gizmo.type %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= gizmo.title %>
  </p>

  <p>
    <strong>Bool1:</strong>
    <%= gizmo.bool1 %>
  </p>

  <p>
    <strong>String1:</strong>
    <%= gizmo.string1 %>
  </p>

  <p>
    <%= link_to "Show this gizmo", gizmo %>
  </p>
</div>

app/views/gizmos/edit.html.erb
<h1>Editing gizmo</h1>

<%= render "form", gizmo: @gizmo %>

<br>

<div>
  <%= link_to "Show this gizmo", @gizmo %> |
  <%= link_to "Back to gizmos", gizmos_path %>
</div>

app/views/gizmos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gizmos</h1>

<div id="gizmos">
  <%= render @gizmos %>
</div>

<%= link_to "New gizmo", new_gizmo_path %>

app/views/gizmos/new.html.erb
<h1>New gizmo</h1>

<%= render "form", gizmo: @gizmo %>

<br>

<div>
  <%= link_to "Back to gizmos", gizmos_path %>
</div>

app/views/gizmos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gizmo %>

<div>
  <%= link_to "Edit this gizmo", edit_gizmo_path(@gizmo) %> |
  <%= link_to "Back to gizmos", gizmos_path %>

  <%= button_to "Destroy this gizmo", gizmo_path(@gizmo), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supertables</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body class='container'>
  <!DOCTYPE html>
  <html>
  <head>
    <title>Supertables</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <% name = current_user.present? ? current_user.email : 'Stranger' %>

  <h1>Welcome, <%= name %> </h1>
  <%= yield %>
  </body>
  </html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
          <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-link nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>